version: "3"

services:
  redis-blue:
    container_name: redis-blue
    image: redis:7.2
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - blue
  
  was-blue:
    container_name: was-blue
    image: suhyun9252/dandi-be:GITHUB_SHA
    restart: always
    volumes:
      - /dandi/logs:/dandi/logs  # log 보존
    ports:
      - "3000:3000"
    env_file:
      - /dandi/.env
    depends_on:
      - redis
    networks:
      - blue
  
  frontend-blue:
    container_name: frontend-blue
    image: suhyun9252/dandi-fe:GITHUB_SHA
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - was
    networks:
      - blue
  
  certbo-bluet:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot-blue
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt 
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - blue

networks:
  blue:
    driver: bridge