version: "3"

services:
  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/data:/data
    ports:
      - "6379:6379"
  
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /dandi/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
      - /dandi/data/certbot/conf:/etc/letsencrypt
      - /dandi/data/certbot/www:/var/www/certbot
    depends_on:
      - frontend-blue
      - was-blue
  
  was-blue:
    container_name: was-blue
    image: suhyun9252/dandi-be:GITHUB_SHA
    restart: always
    volumes:
      - /dandi/logs:/dandi/logs  # log 보존
    ports:
      - "3000:3000"
    env_file:
      - /dandi/.env
    depends_on:
      - redis
  
  frontend-blue:
    container_name: frontend-blue
    image: suhyun9252/dandi-fe:GITHUB_SHA
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /dandi/nginx/dandi-blue.conf:/etc/nginx/conf.d/dandi.conf
      - /var/log/nginx/blue:/var/log/nginx
    depends_on:
      - was-blue