name: CI

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: install dependencies
        run: yarn install

      - name: build frontend
        run: yarn frontend build

      - name: build backend
        run: yarn backend build

      - name: run unit test
        run: yarn backend test

      - name: run e2e test
        run: yarn backend test:e2e
