name: CI

on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install yarn
        run: npm install -g yarn

      - name: install dependency
        run: yarn install

      - name: build frontend
        run: yarn workspace frontend build

      - name: build backend
        run: yarn workspace backend build

      - name: run unit test
        run: yarn workspace backend test
