name: develop CD

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code.
      uses: actions/checkout@v3
              
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/web18-Dandi/ && git stash && git pull origin develop
          yarn install
          yarn frontend build
          yarn backend build
          yarn backend run start:prod