name: develop CD

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code.
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Install yarn
      run: npm install -g yarn
    
    - name: Build with yarn
      run: |
        yarn install
        yarn workspace frontend build
        yarn workspace backend build

    - name: make BE .env
      run: |
        echo "${{ secrets.BE_ENV }}" > .env

    - name: send BE .env
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: .env
        target: /dandi
        overwrite: true
      
    - name: make FE .env
      run: |
        cd frontend
        echo "${{ secrets.FE_ENV }}" > .env

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: make docker images
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-be:${{ github.sha }} -f ./Dockerfile.was .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-be:${{ github.sha }}
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-fe:${{ github.sha }} -f ./Dockerfile.front .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-fe:${{ github.sha }}
    
    - name: make docker-compose files
      run: |  
        sed -i "s/GITHUB_SHA/${{ github.sha }}/g" docker-compose.blue.yml
        sed -i "s/GITHUB_SHA/${{ github.sha }}/g" docker-compose.green.yml
    
    - name: send docker-compose files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: docker-compose.blue.yml docker-compose.green.yml deploy.sh
        target: /dandi
        overwrite: true

    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /dandi
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-be:${{ github.sha }}
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/dandi-fe:${{ github.sha }}
          chmod +x deploy.sh
          ./deploy.sh
#          docker stop $(docker ps -a -q)
#          docker rm $(docker ps -a -q)
#          docker rmi -f $(docker images -q)
#          docker-compose up -d